### ISSUE TITLE
README.md should list aliases and what they map to

### ISSUE THREAD

**Issue by binkley** [spargonaut/.custom_commands#8]
*Narrative*

AS A vulnerable developer
I WANT to see what the aliases are
SO THAT I do not hose my cmd line blindly running code from the Internet

*Acceptance criteria*

GIVEN the completely awesome GitHub support for `README.me`
WHEN I visit https://github.com/spargonaut/.custom_commands
THEN I should see a list of what aliases are made if I blindly follow instructions

**Comment by JAnderton** [comment]
Good point @binkley. I can update the `README.md` to list the commands.

In the long run, we intend to **not** ship commands with this repo and instead provide sub-modules that will allow you to pull in the aliases you need. I envision users pulling submodules for maven, git, git-svn etc. As a result, users will be allowed to extend the solution themselves.

**Comment by spargonaut** [comment]
@binkley, good idea. we _should_ update something (readme, the alias files, etc) to indicate what these commands are doing, as well as what the initialize script is doing.  However, to @JAnderton's point, the real value of this repository (application?) is the initialize script and its associated files.  The included command and alias shortcuts that are included in this repository, serve more as examples of what _could_ be done.

The vision that I have for this application(?), is for users to clone or fork this repository, add their own commands, then push it to their own repository, either on github or on their private repositories.  The command shortcuts could/should be kept small and modular enough to allow for teams to pick and choose which shortcuts they'd like to use, and perhaps share across teams. 

As to your narrative @binkley, one of the things I was thinking about adding, was a check to see if a command is already being used on someones path.  for example, on my centOS box, the command 'gs' starts up ghost script, where as I've seen developers use 'gs' to be a shortcut for 'git status,'  I might put that check in there as an issue and/or just write the check myself.  good thinking.

**Comment by JAnderton** [comment]
@spargonaut: The ideas from the email thread should be converted into github issues. I'd like to tag them as features instead but alas, that requires admin privileges to this repo. *sigh*

I'll add "issues" for the other tasks I mentioned on that thread and work on them :)

**Comment by spargonaut** [comment]
@JAnderton hrmm...  it looks like I gave you all the permissions I was able to, I'm not sure why you can't tag them as features.  I'll see what I can do.

**Comment by JAnderton** [comment]
@spargonaut Never mind. I seem to have the permissions to do it. PEBKAC.
